version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./server
